### ISSUE TITLE
Exception  when calling

### ISSUE THREAD

**Issue by kannangptp** [skrusty/asttray#2]
I getting an Exception while make a call to Extn Number. **"Extension Doesn't Exist"**

my App.config
add key="astHost" value="192.168.1.10"/>
    add key="astPort" value="5038"/>
    add key="astuser" value="104"/>
    add key="astPass" value="123"/>
    add key="astExten" value="104"/>
  add key="astPeerType" value="SIP"/>
    add key="astPeerID" value="105@192.168.1.10"/>
    add key="astExtenContext" value="105@192.168.1.10"/>
    add key="myDirectoryPath" value="local.xml"/>
    add key="sharedDirectoryPath" value="D:\company.xml"/>
    
    add key="sharedDirectoryType" value="CiscoDirectory

**Comment by skrusty** [comment]
```
add key="astPeerID" value="105@192.168.1.10"/>
add key="astExtenContext" value="105@192.168.1.10"/>
```

Those are wrong. See

```
<!-- The extension number assigned to this user -->
    <add key="astExten" value=""/>
    <!-- The peer type, i.e. SIP, IAX -->
    <add key="astPeerType" value="SIP"/>
    <!-- The peer id, this could be different to the extension number -->
    <add key="astPeerID" value=""/>
    <!-- The context you wish the outbound call to be made from (e.g. sip-out) -->
    <add key="astExtenContext" value=""/>
```
