### ISSUE TITLE
What is ScreenPopPath in App.config file?

### ISSUE THREAD

**Issue by kannangptp** [skrusty/asttray#3]
please help me ...What is ScreenPopPath in App.config of Astray application.can  you please give me a  sample path.

**Comment by kannangptp** [comment]
please  help me to solve this issue...

**Comment by skrusty** [comment]
You can find an example in the App.config.example file.

```
<!-- Screen Popping -->
    <!--  Arguments: 
            {callerid-number}    CallerID Number of the inbound call
            {callerid-name}      CallerID Name of the inbound call

          E.g. 
          http://crm.mywebste.co.uk/pop?clid={callerid-number}
    -->
    <add key="ScreenPopPath" value=""></add>
```

https://github.com/skrusty/asttray/blob/master/AstTray/AstTray/App.config.example
